version: "3.5"
services:
  web:
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    links:
      - api
    env_file:
      - .env
    volumes:
      - ./src:/usr/projects/fullstack-resume-frontend/src:ro
      - ./node_modules:/usr/projects/fullstack-resume-frontend/node_modules:ro
  api:
    build: ../backend
    ports:
      - "3001:3001"
    links:
      - database
    env_file:
      - ../backend/.env
  database:
    image: mongo
    logging:
      driver: "none"
    ports:
      - "27017:27017"
