version: "3.5"
services:
  app:
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    links:
      - database
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017
      - DEBUG=frontend:*
    volumes:
      - ./src:/usr/src/app/src:ro
  database:
    container_name: mongo
    image: mongo
    logging:
      driver: "none"
    ports:
      - "27017:27017"
