version: "3.5"
services:
  api:
    container_name: fullstack-resume-backend
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    links:
      - database
    env_file:
      - .env
    volumes:
      - ./src:/usr/projects/fullstack-resume-backend/src:ro
  database:
    container_name: fullstack-resume-mongo
    image: mongo
    logging:
      driver: "none"
    ports:
      - "27017:27017"
